export { ContextEngine } from './engine.js'
export { SQLiteStorage } from './storage/sqlite.js'
export { PostgresStorage } from './storage/postgres.js'
export { LocalEmbeddingProvider } from './embeddings/local.js'
export { OpenAIEmbeddingProvider } from './embeddings/openai.js'
export { createServer } from './server.js'
export { cosineSimilarity, computeDecay, eventToText } from './utils.js'
export type { StoredEvent, EventInput, ContextResult, StorageAdapter, EmbeddingProvider, EngineOptions } from './types.js'
